/*
Taller 2
Fecha: 08-03-2022
Realizado por: Sebastián huertas, Sofia Lopez
*/
var LadoCuadrado=prompt ("ingrese el valor del lado del cuadrado: ");
console.log(LadoCuadrado*LadoCuadrado)
console.log("El lado del cuadrado es " + LadoCuadrado + " y el area del cuadrado es " +  LadoCuadrado**2);
var LadoCubo=prompt ("ingrse el valor de la arista del cubo: ");
console.log(LadoCubo**3)
console.log("la arista del cubo es " + LadoCubo + " y el volumen es " + LadoCubo**3);