console.log("punto 1")
for(var i=1; i<=10; i++){
    console.log(i);    
}

console.log("punto 2")
for(var i=10; i>=1; i--){
    console.log(i);    
}

console.log("punto 3")
var limite=prompt("Ingrese el limite")
var sumatoria=0



console.log("Punto 5")
var arregloNombres
for(var i=0; i<5; i++){
    var nombre=prompt("Ingrese un nombre");
    arregloNombres.push(nombre)
}

console.log(arregloNombres)

console.log("Punto 6")
var arregloNombres
for(var i=0; i<5; i++){
    var nombre=prompt("Ingrese un nombre");
    arregloNombres.push(nombre)
console.log(arregloNombres)
}
for(var i=0; i<arregloNombres.lengt;i++){
    console.log("El nombre ", i, " es ", arregloNombres[i]);
  }