//Archivo de práctica y pruebas de JavaScript.
/* 
Taller1
Fecha 23/02/2022
Realizado por: Sofia Lopez, Sebastián Huertas
*/
var Nombre_del_estudiante; //string
var Grado_estudiante; //string
var Edad_estudiante; //int
Grado_estudiante= "10A";   
Nombre_del_estudiante= "Sofia Lopez, Sebastián Huertas";
var valor= prompt ("Ingrese edad de los estudiantes ");
console.log ("La edad de los estudiantes es " + valor );
console.log ("los estudiantes " + Nombre_del_estudiante + " Del grado " + Grado_estudiante + " tienen " + valor + " años ");
